[DEVOPS-365] Slight (slight) improvement to Dockerfile.
amida-tech/amida-survey-microservice pull request #67
Opened 2018-11-29 02:53 UTC by jmfadeley

**What's this PR do?**
Slightly tweaks the process to allow for correct deployments in Docker. Unfortunately, the survey microservice does not really build a production ready deployment right now. I've created [DEVOPS-366] to handle that. 

**Related JIRA tickets:**
DEVOPS-365, DEVOPS-366.

**How should this be manually tested?**
First, create a network if you haven't already:
`docker network create indaba-network`

Ensure that the docker instance has a database to work with. We're assuming the username and password in your .env are both set to amida, if not then please change. To start a docker instance of a database, run:
`docker run --name survey-db --network indaba-network -e POSTGRES_USER=amida -e POSTGRES_PASSWORD=amida -e POSTGRES_DB=amida-survey-microservice postgres:9.6`

Then run a build in Docker with:
`docker build -t amida-survey-microservice .`

Finally try a deployment. Not that it does NOT go to a `dist` folder as it does not build one yet:
`docker run -p 9005:9005 --name amida-survey-microservice -v <Absolute path to your...>\.env:/usr/src/app/.env -e SURVEY_SERVICE_PG_HOST=survey-db amida-survey-microservice`

If you have any Postman requests, fire them at the endpoint to confirm completion.

**Any background context you want to provide?**
This blocks an ease-of-deployment for Indaba. I am currently trying to get four instances running for four people as simply as possible to cut down on... hour drain.

**Screenshots (if appropriate):**

2018-12-10 17:16 UTC, mountHouli approved these changes
The code looks good to me.

I didn't test anything because I have never run the survey service before.

2018-12-10 21:58 UTC, rmharrison approved these changes

2018-12-10 21:58 UTC, rmharrison commented on Dockerfile
> +RUN yarn install --pure-lockfile
You want `--production --frozen-lockfile`, presumably?

2018-12-10 22:05 UTC, rmharrison reviewed
```
$node seed.js

...
{ SequelizeConnectionError: database "surveyServicetest" does not exist
```

Does this repo need the `create_db` and `delete_db` scripts as well?

2018-12-10 22:30 UTC, rmharrison requested changes
On second glance, a few (minor )questions emerge.

2018-12-10 22:30 UTC, rmharrison commented on test/shared.integration.js
> +const config = require('../config/config');
```
$ yarn test

Error: Cannot find module '../config/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/work/git/amida-tech/amida-survey-microservice/test/shared.integration.js:16:16)
```

2018-12-10 22:30 UTC, rmharrison commented on CHANGELOG.md
> +# Changelog
Please remove windows end of lines
```
diff --git a/CHANGELOG.md b/CHANGELOG.md
new file mode 100644
index 00000000..0feaec93
--- /dev/null
+++ b/CHANGELOG.md
@@ -0,0 +1,5 @@
+# Changelog^M
+^M
+- Slimmer Dockerfile settings.^M
+^M
+# [Unreleased]^M
```

2018-12-10 22:30 UTC, rmharrison commented on CHANGELOG.md
> +# Changelog
`RELEASENOTES.md` should be renamed `CHANGELOG.md`

2018-12-10 22:30 UTC, rmharrison commented on test/shared.integration.js
> +const config = require('../config/config');
Test (5464) pass for both `const config = require('../config');` and `const config = require('../config/test');`

2018-12-11 17:17 UTC, jmfadeley commented
@rmharrison looking at these concerns now. They're slightly out of scope for what I intended but since I'm here might as well.

2018-12-11 18:33 UTC, jmfadeley commented
@rmharrison Pushed an update that includes the `create_db` and `delete_db` scripts. You will need to run `yarn` in order to install a couple of new packages, then run `yarn test` to test the results. For the `Dockerfile`, you want it to run the whole gauntlet like we do on the other services?

2018-12-18 20:25 UTC, rmharrison approved these changes

2018-12-18 20:28 UTC, rmharrison commented on Dockerfile
> +RUN yarn install --pure-lockfile
Nope. Non-production is intentional.

Proximal
- cross-env is in dev deps, and is required by `create_db`, `delete_db` and `seed`

Root
- `yarn serve` requires some dev deps because there's not build step
- config isn't entirely loaded from `.env`
- seed script isn't on sequelize.

2018-12-18 22:17 UTC, rmharrison commented
@jmfadeley All comments resolved. Approved.

2018-12-19 16:02 UTC, merged